#!/bin/bash

#PBS -P ut81
#PBS -l ncpus=27
#PBS -l mem=14gb
#PBS -l walltime=24:00:00
#PBS -k oe

# Setup email notifications when the job is aborted(a), begins (b) or ends (e)
#PBS -M Gavin.Cooper@uon.edu.au
#PBS -m abe

#PBS -q normal

source /etc/profile.d/modules.sh 
module load R/4.2.2

cd $PBS_O_WORKDIR

Rscript --no-save --no-restore src/model_estimation.R > estimation_$MCCE_EST_EXP.$VDCE_TAG.$PBS_JOBID.out 2> estimation_$MCCE_EST_EXP.$VDCE_TAG.$PBS_JOBID.err

exit 0
