#!/bin/bash
#PBS -l select=1:ncpus=26:mem=12gb
#PBS -l walltime=12:00:00
#PBS -k oe

# Setup email notifications when the job is aborted(a), begins (b) or ends (e)
#PBS -M gavin@gavincooper.net
#PBS -m abe

source /etc/profile.d/modules.sh 
module load R/3.6.3

cd $PBS_O_WORKDIR
tag="IST_Try1"

Rscript --no-save --no-restore src/model_recovery_task1.R > data/output/recovery_Exp1_$tag.$PBS_JOBID.out 2> data/output/recovery_Exp1_$tag.$PBS_JOBID.err

exit 0
