#!/bin/bash
#PBS -l select=1:ncpus=26:mem=14gb
#PBS -l walltime=24:00:00
#PBS -k oe
#PBS -v DCE_EST_EXP=NumericVDCE,VDCE_TAG=TestDevPMWG2

# Setup email notifications when the job is aborted(a), begins (b) or ends (e)
#PBS -M gavin@gavincooper.net
#PBS -m abe


source /etc/profile.d/modules.sh 
module load R/4.0.1

cd $PBS_O_WORKDIR

Rscript --no-save --no-restore src/model_estimation_Exp1.R > vdce_1_$VDCE_TAG.out 2> vdce_1_$VDCE_TAG.err

exit 0
