#!/bin/bash
#PBS -l select=1:ncpus=15:mem=14gb
#PBS -l walltime=24:00:00
#PBS -k oe

# Setup email notifications when the job is aborted(a), begins (b) or ends (e)
#PBS -M gavin@gavincooper.net
#PBS -m abe


source /etc/profile.d/modules.sh 
module load R/4.0.1

cd $PBS_O_WORKDIR

export VDCE_DISPLAY="Absent"
tag="CorrectedTry1"

Rscript --no-save --no-restore src/model_estimation_Exp2.R $tag > vdce_2_absent_$tag.out 2> vdce_2_absent_$tag.err

exit 0
